### ISSUE TITLE
problems (Error 43)

### ISSUE THREAD

**Issue by alexdibi** [cruwaller/rc_receiver_to_usb_hid#1]
I think there is a boot problem on some PCs I am given error 43 (device not recognized) but if connected via a hub it works, reading around as I am not very familiar with stm32, reading on the various forums I realized that Windows decides that  the device is not recognized before the boot phase is finished, uninstalling and reinstalling or drivers once it is already connected to the PC in fact it works

**Comment by cruwaller** [comment]
Thanks for the info!
I haven't seen the similar issue. Need to double check it.
USB stack code based on STs reference implementation and that is used widely (e.g. betaflight and opentx use the same stack as well). 

Btw, could it be a power issue? Have you tried other good quality usb cable?

**Comment by cruwaller** [comment]
And btw, which kind of bluepill you have? There are different versions available and some of those are worst than others...

**Comment by alexdibi** [comment]
![PXL_20210220_091610577.jpg](https://user-images.githubusercontent.com/52356568/108592867-6603f980-7370-11eb-8031-20c294e234e7.jpg)
![PXL_20210220_091548314.jpg](https://user-images.githubusercontent.com/52356568/108592869-68feea00-7370-11eb-9657-02d8bd6b1cec.jpg)
I don't know if the photos of my bluepill can help you

**Comment by alexdibi** [comment]
https://www.elektroda.com/rtvforum/topic2370966.html

**Comment by cruwaller** [comment]
Thanks for the pictures!
There is the known issue with the D+ pullup resistor (external not needed and STM handles that internally). You can try to remove R10 to see if that fixes your issue.

**Comment by alexdibi** [comment]
or I try to bypass it with a piece of wire, if I take it off, I lose it for sure

**Comment by cruwaller** [comment]
You cannot bypass it! It will short so remove it :)

**Comment by alexdibi** [comment]
removing the R10 is powered but the PC does not see anything

**Comment by alexdibi** [comment]
After several tests even with lower value resistors since the R10 on mine is 10k, the problem persists so I put the stock resistor back and order another bluepill, however I also found this solution, but I don't know if it actually works:
http://amitesh-singh.github.io/stm32/2017/05/27/Overcoming-wrong-pullup-in-blue-pill.html
![Screenshot_2021-02-20-23-25-18-803_com.android.chrome.jpg](https://user-images.githubusercontent.com/52356568/108610128-84e7a780-73d3-11eb-87ea-5b02c60ae02e.jpg)

**Comment by cruwaller** [comment]
hmm, let's try... I will make change to code and push into a branch...

**Comment by cruwaller** [comment]
I added init for PA12 pin and code is pushed into branch: 
https://github.com/cruwaller/rc_receiver_to_usb_hid/tree/fix_bluepill_usb
Please try that, hope it solves the issue :)

**Comment by alexdibi** [comment]
works great now!

**Comment by cruwaller** [comment]
Wow, that is great! I will merge it to master then. 
Thanks a lot!

Happy flying 👍

**Comment by cruwaller** [comment]
Fix merged into master.
